### ISSUE TITLE
After update to 2.1.5

### ISSUE THREAD

**Issue by ViTVetal** [hbb20/CountryCodePickerProject#173]
` java.lang.NoClassDefFoundError: Failed resolution of: Lio/michaelrocks/libphonenumber/android/PhoneNumberUtil;
                                                     at com.hbb20.CountryCodePicker.updateFormattingTextWatcher(CountryCodePicker.java:805)
                                                     at com.hbb20.CountryCodePicker.setEditText_registeredCarrierNumber(CountryCodePicker.java:1001)
                                                     at com.hbb20.CountryCodePicker.registerCarrierNumberEditText(CountryCodePicker.java:1584)
                                                     at com.vitvetal_taxi.taxiclient.ui.activities.SignInActivity.onCreate(SignInActivity.java:64)
                                                     at android.app.Activity.performCreate(Activity.java:6357)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
                                                     at android.app.ActivityThread.access$1000(ActivityThread.java:154)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:157)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5555)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "io.michaelrocks.libphonenumber.android.PhoneNumberUtil" on path: DexPathList[[zip file "/data/app/com.vitvetal_taxi.taxiclient-2/base.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.vitvetal_taxi.taxiclient-2/lib/arm64, /data/app/com.vitvetal_taxi.taxiclient-2/base.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.vitvetal_taxi.taxiclient-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.hbb20.CountryCodePicker.updateFormattingTextWatcher(CountryCodePicker.java:805) 
                                                     at com.hbb20.CountryCodePicker.setEditText_registeredCarrierNumber(CountryCodePicker.java:1001) 
                                                     at com.hbb20.CountryCodePicker.registerCarrierNumberEditText(CountryCodePicker.java:1584) 
                                                     at com.vitvetal_taxi.taxiclient.ui.activities.SignInActivity.onCreate(SignInActivity.java:64) 
                                                     at android.app.Activity.performCreate(Activity.java:6357) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515) 
                                                     at android.app.ActivityThread.access$1000(ActivityThread.java:154) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:157) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5555) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635) 
                                                 	Suppressed: java.lang.ClassNotFoundException: io.michaelrocks.libphonenumber.android.PhoneNumberUtil
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                 		at java.lang.ClassLoader.loadClass(ClassLoader.java:`

**Comment by Arasthel** [comment]
Worked around by adding the library and its dependencies:

```groovy
    implementation 'com.hbb20:ccp:2.1.5'
    implementation 'io.michaelrocks:libphonenumber-android:8.8.5'
    implementation 'com.futuremind.recyclerfastscroll:fastscroll:0.2.5'
```

Maybe the jar wasn't generated properly? Or need to change `implementation` for those 2 dependencies to `api` on CCP sources, not sure.

**Comment by etanhatch** [comment]
It seems that library dependencies are not automatically retrieved. I needed to add the following:

    compile 'io.michaelrocks:libphonenumber-android:8.9.0'
    compile 'com.futuremind.recyclerfastscroll:fastscroll:0.2.5'

**Comment by hbb20** [comment]
Sorry for the trouble.
Actually, something is broken in library uploader config (bintrayUpload) due to changing gradle version and implementation. I tried with api as well but without success. So temporarily, I have switched back to compile. You can use version 2.1.9. Meanwhile, I will look for a way to change from compile to implementation or api.
